### ISSUE TITLE
Error saying it is not supported on iOS

### ISSUE THREAD

**Issue by raefa** [triniwiz/nativescript-videorecorder#1]
Thanks for putting the app out. 

I note that when building see this in the logs:
`nativescript-videorecorder is not supported for ios.`

It subsequently does not work because the module is not there. Can you get it to run on iOS?

**Comment by triniwiz** [comment]
Sorry ios is not supported atm but I'm sure someone awesome would add support for it soon 😊.

**Comment by raefa** [comment]
Ahhh ... sorry. I must be seeing things. I thought I read that it was cross platform already! No dramas. I am hoping someone will support it soon too. Sorry ... I don't have the skills to do it.

**Comment by triniwiz** [comment]
I would of but I don't own a Mac yet 😂 so I'll see if I get someone to do it

**Comment by victorsosa** [comment]
HI guys,

 I committed a PR #2 to implemented the IOS part; this is beta.

```
var vr = require("nativescript-videorecorder");
var videorecorder = new vr.VideoRecorder();
var options = {
    saveToGallery:true, //default false | optional
    duration:0.0, //The maximum duration, in seconds, permitted for trimmed movies saved by the video editor. default no limit | optional
    quallity:0, //default  0-5| optional
}
videorecorder.record(options)
.then((data)=>{
    console.log(data.filePath)
})
.catch((err)=>
{console.log(err)})
```

**Comment by triniwiz** [comment]
@raefa yupdate your plugin to enjoy the ios goodness @victorsosa has added :smile:

**Comment by raefa** [comment]
Great stuff! Will try it out. :)
