### ISSUE TITLE
IOS support

### ISSUE THREAD

**Issue by IvRRimum** [triniwiz/nativescript-videorecorder#10]
Does this work for IOS too?

**Comment by triniwiz** [comment]
Yes but I think it needs a small patch

**Comment by Daxito** [comment]
@triniwiz So, what is the patch about?

**Comment by triniwiz** [comment]
check https://github.com/triniwiz/nativescript-videorecorder/issues/7#issue-165934388

**Comment by triniwiz** [comment]
Fixed https://github.com/triniwiz/nativescript-videorecorder/commit/64e39c5084251622cf862538613555939b5215cf
