### ISSUE TITLE
saveToGallery:true not working on android

### ISSUE THREAD

**Issue by DavidBabel** [triniwiz/nativescript-videorecorder#13]
Hey !

I tried this plugin on android 6.0.1 and it seems on stock cyanogen camera, this option is not working, since the video is present in the galery.

Regards

**Comment by triniwiz** [comment]
@DavidBabel interesting i'll need to look into this

**Comment by DavidBabel** [comment]
I did not noticed it before, but the data.file returned, refer to an inexistant file either.

**Comment by triniwiz** [comment]
@DavidBabel worked fine last time i tested because it wired the videoplayer

**Comment by triniwiz** [comment]
Fixed in the new release 😄
