### ISSUE TITLE
plugin error : camera permission needed

### ISSUE THREAD

**Issue by GrEg00z** [triniwiz/nativescript-videorecorder#16]
Hello,

I get this error when I try to record a video : 

`{"event":"camera permission needed"}`

I use this code (with **Nativescript angular**)

`var videorecorder = new vr.VideoRecorder();`
                `videorecorder.record(options)`
                `.then((data)=>{`
                    `console.log("VIDEO TAKE")`
                    `console.log("data : ", JSON.stringify(data))`
               ` })`
               ` .catch((err)=>{`
                   ` console.log(JSON.stringify(err))`
               ` })`

I have also tried to force the **CAMERA permission** with the plugin nativescript-permissions, but it still display the error

**Comment by minitru** [comment]
Try adding the permissions to AndroidManifest.xml and doing a full rebuild.

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.CAMERA" />

**Comment by GrEg00z** [comment]
Thanks for your help @minitru, I tried your solution but it still doesn't work

I get the same error message `{"event":"camera permission needed"}`

**Comment by ButterMeWaffle** [comment]
I am also having this issue, as of a new update today on my LG G5 i am getting this 

`{"event":"camera permission needed"}`

However i am asking for the camera permission using the NS camera module

`camera.requestPermissions();`

I have also checked the apps permissions and it does have the camera permission checked. any ideas on how to resolve this?

**Comment by AbdallahBedir** [comment]
adding the permissions to AndroidManifest.xml and still have the error

**Comment by ButterMeWaffle** [comment]
@AbdallahBedir I did the same, still did not fix it

**Comment by triniwiz** [comment]
This should be fixed in the recent release
