### ISSUE TITLE
Android : Recording fail after 4s when READ_EXTERNAL_STORAGE 

### ISSUE THREAD

**Issue by GrEg00z** [triniwiz/nativescript-videorecorder#23]
Version : 
 - nativescript-videorecorder : 3.0.0
 - nativescript : 3.0.0
 - tns-android : 3.0.0
 - android 7.1.1 on Nexus 5X

After adding **READ_EXTERNAL_STORAGE** permission to my nativecript app and request it via nativescript-permission plugin, then when I start a video recording, it records 4 seconds and stops by itself
**The video are not saved in gallery !**

But If my app don't use **READ_EXTERNAL_STORAGE**, the recording works great and it well saved in my gallery

It's very problematic because I try to extract videos from gallery and to send it to my api server, so I need to have **READ_EXTERNAL_STORAGE** permission in my app

**Comment by Ghits-nl** [comment]
I have the same issue in some Android devices
