### ISSUE TITLE
Android saveToGallery issue

### ISSUE THREAD

**Issue by ButterMeWaffle** [triniwiz/nativescript-videorecorder#26]
On Android only.

When you set `saveToGallery: true` it does not open the camera and throws this error 
`JS: {"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}`

my temporary solution (since i use iOS as well)
`if (this.app.android) {
            var options = {
                saveToGallery: true, //default false | optional
                format: 'mp4',
                //duration: 300, //(seconds) default no limit | optional
                //size: 100, //(MB) default none | optional #android
                hd: true, //default  false low res | optional
                explanation: "To record video..." //optional on api 23 #android
            }
        } else {
            var options = {
                saveToGallery: false, //default false | optional
                format: 'mp4',
                //duration: 300, //(seconds) default no limit | optional
                //size: 100, //(MB) default none | optional #android
                hd: true, //default  false low res | optional
                explanation: "To record video..." //optional on api 23 #android
            }
        }`

**Comment by ButterMeWaffle** [comment]
update - there seems to be anew error - `TypeError: Cannot read property 'toURI' of undefined`

**Comment by mrazahasan** [comment]
`saveToGallery: true` but still file is not creating on provided path.

**Comment by triniwiz** [comment]
The next release should fix this
