### ISSUE TITLE
Feature Request: add stop()/pause()/resume() methods to recorder

### ISSUE THREAD

**Issue by gtnunes1956** [triniwiz/nativescript-videorecorder#29]
It would be a useful enhancement for this plugin to have a 'stop()' feature available. Moreover, the possibility to pause and resume recording within the same configuration state would also be a plus. Incidentally, all those features are available natively on both Android and iOS environments.

**Comment by triniwiz** [comment]
So there is the advanced camera view i'm working on there is stop but i'll look into adding the pause and resume
