### ISSUE TITLE
NativeScript-Permissions dependency

### ISSUE THREAD

**Issue by NathanaelA** [triniwiz/nativescript-videorecorder#3]
Instead of putting this into your repo; you can declare it as a dependency of your plugin.  That way if I fix a bug; you get it.  ;-)

i.e. add to your package.json: 
   dependencies: { "nativescript-permissions": "latest" }
and then you just do a 
   var np = require('nativescript-permissions'); 

This keeps your repo clean...  ;-)

**Comment by victorsosa** [comment]
Hi,
I see you point. Yea, you are right.

**Comment by triniwiz** [comment]
@NathanaelA thanks for the tip :+1:
