### ISSUE TITLE
NS3.1 Android Camera permission needed

### ISSUE THREAD

**Issue by olehau** [triniwiz/nativescript-videorecorder#30]
Hi.

I'm trying to use this on NS 3.1 for android, but all I get is the following error:
{"event":"camera permission needed"}.

I just installed the latest version of the plugin.

My initialization code looks like this:

```
    var options = {
        saveToGallery: false,
        duration: parseInt(record_time),
        format: 'mp4',  
        position: 'front',
        hd:true, 
        explanation: "To record video for interviews"
    }
    videorecorder.record(options)......

```
When I try to start the recording it fails with the above error message. I never get the permission boxes to agree with the permissions.
However. If I add this to the app.js file, I get them, and can accept:

```
if( application.android ){
permissions.requestPermission([android.Manifest.permission.CAMERA, android.Manifest.permission.RECORD_AUDIO], "I need these permissions because I'm cool")
  .then(function() {
     console.log("Woo Hoo, I have the power!");
  })
  .catch(function() {
     console.log("Uh oh, no permissions - plan B time!");
  });
}
```

However, if I request the permissions manually in app.js and then try to start a recording. it fails with this error message (empty object):

`{}`

I've also added this to my AndroidManifest.xml:

```
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>
	<uses-permission android:name="android.permission.RECORD_AUDIO" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-feature android:name="android.hardware.camera" />
	<uses-feature android:name="android.hardware.camera.autofocus" />	
```

**Comment by olehau** [comment]
After some more debugging, the problem seems to be in src/android/video-recorder.js on line 38:
intent.putExtra(android.provider.MediaStore.EXTRA_OUTPUT, file.toURI());

TypeError: Cannot read property 'toURI' of undefined

**Comment by ButterMeWaffle** [comment]
Thanks for putting the time into fixing this @olehau

**Comment by ghost** [comment]
I have the very same issue.

**Comment by ButterMeWaffle** [comment]
@Feather-CMS have you requested the record audio permission? using the permission plugin

**Comment by ghost** [comment]
Hi, It works , however It was not working while connected to my machine (cable / MPB) interestingly, only in the morning I found out it was working.
Not used the permission plugin.

**Comment by ghost** [comment]
I have the issue now it does not store the video on the phone, investigating .

**Comment by ButterMeWaffle** [comment]
@Feather-CMS do you have it set to save the video?

**Comment by ghost** [comment]
here 

var options = {
    saveToGallery:true, //default false | optional 
    duration:30, //(seconds) default no limit | optional 
    format:'mp4', //allows videos to be played on android devices | optional | recommended for cross platform apps 
    size:10, //(MB) default none | optional #android 
    hd:true, //default  false low res | optional 
    explanation:"Why do i need this permission" //optional on api 23 #android 
}

**Comment by ghost** [comment]
got it working  by setting options.hd to false.

**Comment by ButterMeWaffle** [comment]
I believe there is currently an issue with hs as well as duration. However i believe duration only causes a quality issue. @Feather-CMS

**Comment by triniwiz** [comment]
@Feather-CMS you can check out the v3 there is some new features where you can set the video quality plus more also this issue was fixed
