### ISSUE TITLE
Getting wrong name in Android

### ISSUE THREAD

**Issue by jibon57** [triniwiz/nativescript-videorecorder#32]
Hello,

Thanks for the plugin. I am tying to use this plugin but after successfully completing the record it giving wrong file name. I checked the recorded file name & output file name isn't same. Anyone can help me please?

Thanks

**Comment by jibon57** [comment]
OK, got the solution. Will do a pull request later. 

```
let nativeFile;
		let path;
		let tempPictureUri;
		let fileName = "videoCapture_" + Date.now() + ".mp4";
		
        if (!options.saveToGallery) {
          path = utils.ad.getApplicationContext().getExternalFilesDir(null).getAbsolutePath() + "/" + fileName;
          nativeFile = new java.io.File(path);

        } else {
          path = android.os.Environment.getExternalStoragePublicDirectory(android.os.Environment.DIRECTORY_DCIM).getAbsolutePath() + "/Camera/" + fileName;
          nativeFile = new java.io.File(path);
        }
```

**Comment by ghost** [comment]
Is this plugin maintained? This issue is 3 months old and there is no response from the maintainer and the bug is still present.

**Comment by triniwiz** [comment]
I’m around just busy but I have some updates planned for this plugin in a day or two
