### ISSUE TITLE
Video file is not created on the returned path

### ISSUE THREAD

**Issue by Sharique-Hasan** [triniwiz/nativescript-videorecorder#35]
Video recorder is not creating file on the path returned from the plugin on Nexus6 with Android 7.1.1. However it is creating correct file on other devices.

**Comment by topara** [comment]
The same happened in huawei p8 andrid 5,1

**Comment by topara** [comment]
Did someone found the solution?

**Comment by topara** [comment]
Here's teh solution:
app.android.currentContext.onActivityResult = function (requestCode, resultCode, data) {
						if (requestCode === REQUEST_VIDEO_CAPTURE && resultCode === RESULT_OK) {
							let mediaFile=data.getData();
									if (options.saveToGallery) {
										resolve({ file: mediaFile.getPath() });
									} else {
										resolve({ file:  mediaFile.getPath() });
									}
						}
						else if (resultCode === RESULT_CANCELED) {
                            reject({ event: 'cancelled' })
                        } else {
                            reject({ event: 'failed' })
                        }
					}

**Comment by Mubashir-Mohamed** [comment]
For me, the video is getting recorded but when I try to show it in my app its saying its undefined. Can anyone help me solve this issue

**Comment by triniwiz** [comment]
Everyone here can try the v3 with the new camera view (would love some feedback) or they can stick with regular view also the next release has a fix for this

**Comment by triniwiz** [comment]
Update away 😄
