### ISSUE TITLE
Application returning error when giving "npm run demo.android" command

### ISSUE THREAD

**Issue by Suralal001** [triniwiz/nativescript-videorecorder#36]
When i try run the command npm run demo.android
it is returning the error:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Neoito\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'demo.android' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose run-script [ 'predemo.android', 'demo.android', 'postdemo.android' ]
5 info lifecycle nativescript-videorecorder@2.0.2~predemo.android: nativescript-videorecorder@2.0.2
6 info lifecycle nativescript-videorecorder@2.0.2~demo.android: nativescript-videorecorder@2.0.2
7 verbose lifecycle nativescript-videorecorder@2.0.2~demo.android: unsafe-perm in lifecycle true
8 verbose lifecycle nativescript-videorecorder@2.0.2~demo.android: PATH: C:\Users\Neoito\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Neoito\app\Nativescript\nativescript-videorecorder-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Dentrix\;C:\android-sdk;C:\Program Files\Java\jdk1.8.0_144;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Java\jdk1.8.0_144;C:\Program Files (x86)\MongoDB\Server\3.2\bin;C:\Users\Neoito\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Neoito\AppData\Local\Microsoft\WindowsApps;C:\Users\Neoito\AppData\Local\Programs\Fiddler;C:\Users\Neoito\AppData\Roaming\npm;C:\Users\Neoito\AppData\Local\Microsoft\WindowsApps;C:\Users\Neoito\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle nativescript-videorecorder@2.0.2~demo.android: CWD: C:\Users\Neoito\app\Nativescript\nativescript-videorecorder-master
10 silly lifecycle nativescript-videorecorder@2.0.2~demo.android: Args: [ '/d /s /c',
10 silly lifecycle   'npm run preparedemo ; cd demo ; tns run android' ]
11 silly lifecycle nativescript-videorecorder@2.0.2~demo.android: Returned: code: 2  signal: null
12 info lifecycle nativescript-videorecorder@2.0.2~demo.android: Failed to exec demo.android script
13 verbose stack Error: nativescript-videorecorder@2.0.2 demo.android: `npm run preparedemo ; cd demo ; tns run android`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Neoito\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Neoito\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nativescript-videorecorder@2.0.2
15 verbose cwd C:\Users\Neoito\app\Nativescript\nativescript-videorecorder-master
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Neoito\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "demo.android"
18 verbose node v8.9.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error nativescript-videorecorder@2.0.2 demo.android: `npm run preparedemo ; cd demo ; tns run android`
22 error Exit status 2
23 error Failed at the nativescript-videorecorder@2.0.2 demo.android script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by triniwiz** [comment]
Please update
