### ISSUE TITLE
App crashes after starting video-recorder on iOS

### ISSUE THREAD

**Issue by FarruchKouliev** [triniwiz/nativescript-videorecorder#47]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
App crashes after Start whithout NS-Errors, when using video-recorder on iOS. However, there are some errors in the simulator logs, as listed below. 

### Which platform(s) does your issue occur on?
- iOS
- iOS 10.3
- emulator 

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 
- "tns-core-modules": "^4.1.0",
- Runtime(s): 
- "tns-ios": "4.1.1"
- Plugin(s): 
- "nativescript-videorecorder": "^3.0.0-alpha.11"

### Please, tell us how to recreate the issue in as much detail as possible. 

1. Create HelloWorld-Example: https://docs.nativescript.org/angular/start/hello-world/ng-chapter-1
1. tns plugin add nativescript-videorecorder
1. Modify app.component.ts & app.component.html as described below
1. tns run ios
1. Error occurs in simulator log: 

- Jul  1 15:40:18 Farruchs-MBP com.apple.CoreSimulator.SimDevice.27CB9A88-4C13-4F9A-A242-7DDC13EF516D[2339] (UIKitApplication:org.nativescript.HelloWorld[0x5da8][2360][36146]): Service exited due to Segmentation fault: 11

- Jul  1 15:40:18 Farruchs-MBP SpringBoard[2355]: [KeyboardArbiter] HW kbd: Failed to set (null) as keyboard focus

- Jul  1 15:40:22 Farruchs-MBP assertiond[2360]: Deleted job with label: UIKitApplication:org.nativescript.HelloWorld[0x5da8][2360]

### Is there any code involved? 
 **app.component.ts:**
```
import { Component } from "@angular/core";
import { VideoRecorder, Options as VideoRecorderOptions } from 'nativescript-videorecorder';

@Component({
  selector: "my-app",
})

export class AppComponent {
    public ngOnInit(): void {
        const videorecorder = new VideoRecorder();
        videorecorder.record().then((data) => {
            console.log(data.file)
        }).catch((err) => {
            console.log(err)
        });
    }
}
```

**Comment by triniwiz** [comment]
The plugin won't work on the ios simulator

**Comment by FarruchKouliev** [comment]
Ok, can you give me some insights why it‘s not possible? Meaning, is it not possible in general on iOS, or in NativeScript or does the plugin need to be extended?
And does it work on a real device?

**Comment by triniwiz** [comment]
In general for iOS

**Comment by klever34** [comment]
@triniwiz on android device, when I set the HD to true, the app crashes

**Comment by triniwiz** [comment]
@klever34 sounds like you are using the standard recorder I’ll have to look into that

**Comment by klever34** [comment]
@triniwiz Okay should I wait for a feedback?

**Comment by triniwiz** [comment]
@klever34 you can always try out the `AdvancedVideoView`
