### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by joey0xx** [triniwiz/nativescript-videorecorder#50]
Getting this error when building the app.

C:\...\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\6e16995b85ad0a68e11f77ec59e559b3\res\values-v28\values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\...\platforms\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml:11: AAPT: error: resource android:attr/dialogCornerRadius not found.

C:\...\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\6e16995b85ad0a68e11f77ec59e559b3\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\...\.gradle\caches\transforms-1\files-1.1\appcompat-v7-28.0.0.aar\6e16995b85ad0a68e11f77ec59e559b3\res\values\values.xml:1304:5-69: AAPT: error: resource android:attr/ttcIndex not found.

The version of the plugin is "nativescript-videorecorder": "^3.0.0-beta.0",

**Comment by triniwiz** [comment]
You can try updating to `3.0.0-beta.1`
