### ISSUE TITLE
AdvancedVideoView - what is it?

### ISSUE THREAD

**Issue by cfjedimaster** [triniwiz/nativescript-videorecorder#64]
Title pretty much says it all. In the readme, the AdvancedVideoView is documented but nothing described what it is. Even one sentence would help.

**Comment by Tronix117** [comment]
AdvancedVideoView does not open the device camera application, but rather allow you to embed the camera view in your app. You can then add the buttons over it to start/stop recording, etc...
It allows you for more customisation

**Comment by cfjedimaster** [comment]
Thanks - copied (and slightly modified this) into a PR.
