### ISSUE TITLE
You can use the advanced camera class where you can control most of that 🙂

### ISSUE THREAD

**Issue by Ghits-nl** [triniwiz/nativescript-videorecorder#74]
You can use the advanced camera class where you can control most of that 🙂

_Originally posted by @triniwiz in https://github.com/triniwiz/nativescript-videorecorder/issues/55#issuecomment-459547254_

Is this class working on Android?

**Comment by triniwiz** [comment]
Yes an updating is coming soon to upgrade the android core to 1.x of the lib

**Comment by Ghits-nl** [comment]
> Yes an updating is coming soon to upgrade the android core to 1.x of the lib

Ok, Please let me know when the upgrade is ready. I am realy need it. Thank you in advance
