### ISSUE TITLE
sdkVersion error

### ISSUE THREAD

**Issue by maganius** [triniwiz/nativescript-videorecorder#81]
When execute the video record ` videorecorder.record()` the console throw an error ` Cannot read property 'sdkVersion' of undefined`

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both - **Android**
- iOS/Android versions - **Android 10**
- emulator or device. What type of device? - **Device**

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) - **7.0.10**
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) - **folders doesnt exists**
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

```
"dependencies": {
    "@nativescript/core": "~7.0.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-image": "^3.0.12",
    "nativescript-ui-sidedrawer": "~9.0.0",
    "nativescript-videorecorder": "^3.0.0-beta.6",
    "nativescript-vue": "~2.8.0",
    "rxjs": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "@nativescript/android": "7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "babel-loader": "~8.0.0",
    "nativescript-vue-template-compiler": "~2.8.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.9.3"
  },
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

I just install the plugin and start the camera record, its nativescript-vue app
```
recordVideo() {
                console.log('tap')
                // vm.set('error', '');
                videorecorder.record().then(data => {
                    if (data && data.file) {
                        console.log(data.file)
                        // vm.set('selectedVideo', data.file);
                    }
                }).catch((err) => {
                    console.log(err.event || err.message)
                    // vm.set('error', err.event || err.message);
                });
            }
```

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by triniwiz** [comment]
Fixed in `@triniwiz/nativescript-videorecorder`
