### ISSUE TITLE
Videorecorder is not working on iOS 14

### ISSUE THREAD

**Issue by Natszen** [triniwiz/nativescript-videorecorder#82]
### Which platform(s) does your issue occur on?
Error occurs on device with iOS 14

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.11
- Cross-platform modules: 7.0.13
- Runtime(s): 7.0.6
- Plugin(s): 4.0.0

### Please, tell us how to recreate the issue in as much detail as possible. 
I use plugin as defined in documentation. It works fine on Android however on iOS after calling method record video recorder show up, it's possible to create video and accept it, but after that nothing happens. Method record never receives result or error.
In console i can see many outputs, the most important in my opinion is "Failed to read exposureBiasesByMode dictionary: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: data is NULL}"

In Info.plist I have permissions for NSCameraUsageDescription and NSMicrophoneUsageDescription with descriptions.

### Is there any code involved? 
```
import { VideoRecorder, Options as VideoRecorderOptions } from '@triniwiz/nativescript-videorecorder';

options: VideoRecorderOptions = {
    hd: true,
    saveToGallery: false
  }
  videorecorder = new VideoRecorder(this.options);

record() {
    this.videorecorder.requestPermissions();
    this.videorecorder.record()
      .then((data) => {
        this.videoSrc = data.file;
      }).catch((err) => {
        console.log('video error', err)
      })
  }
```

**Comment by triniwiz** [comment]
fixed in `@triniwiz/nativescript-videorecorder version 4.0.2`
