### ISSUE TITLE
saveToGallery:false not working on android nativescript 7

### ISSUE THREAD

**Issue by mamuncse1112** [triniwiz/nativescript-videorecorder#83]
Here is my code,
const options: VideoRecorderOptions = {
			hd: false,
			saveToGallery: false
		}
		const videorecorder = new VideoRecorder(options)
        videorecorder.record().then((data) => {
			console.log("Path" , data.file)
          
		}).catch((err) => {
			console.log(err)
		})

**Comment by triniwiz** [comment]
Any error ?

**Comment by mamuncse1112** [comment]
No..... videorecorder.record() function not executed.... If SaveToGalary : false

**Comment by mamuncse1112** [comment]
@triniwiz/nativescript-videorecorder version 4.0.1

**Comment by triniwiz** [comment]
fixed in `@triniwiz/nativescript-videorecorder version 4.0.2`
